spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///openapi-admin?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
